name: Concurrency Example

on:
  push:
    branches:
      - main

concurrency:
  group: main-deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: sleep 30000
