name: print firt pipeline

on:
  push:
    branches:
      - main

jobs:
  naveen:
    runs-on: 	ubuntu-latest
    steps:
      - name: showing demo to naveen
        run: echo "hello i am naveen"
      - name: mentor by shaik
        run: echo "mentor by shaik"
      - name: print linux command
        run: |
          pwd
          whoami
          date
          du
          free
        
    
    

